name: Publish

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - run: mkdir bin

      - name: Get Version
        id: vars
        run: echo ::set-output name=version::$(echo ${{github.ref_name}} | sed 's/^v//')

      - name: Write Version file
        run: |
          touch VERSION
          echo ${{steps.vars.outputs.version}} > VERSION

      - name: Compile for Linux arm64
        run: |
          deno compile \
            --target=aarch64-unknown-linux-gnu \
            --output=bin/staticalize-linux-arm64 \
            --include=VERSION \
            --allow-read --allow-write --allow-net main.ts

      - name: Compile for macOS arm64
        run: |
          deno compile \
            --target=aarch64-apple-darwin \
            --output=bin/staticalize-macos-arm64 \
            --include=VERSION \
            --allow-read --allow-write --allow-net main.ts

      - name: Compile for Linux x64
        run: |
          deno compile \
            --target=x86_64-unknown-linux-gnu \
            --output=bin/staticalize-linux \
            --include=VERSION \
            --allow-read --allow-write --allow-net main.ts
  
      - name: Compile for Windows x64 
        run: |
          deno compile \
            --target=x86_64-pc-windows-msvc \
            --output=bin/staticalize-windows \
            --include=VERSION \
            --allow-read --allow-write --allow-net main.ts  

      - name: Compile for macOS x64
        run: |
          deno compile \
            --target=x86_64-apple-darwin \
            --output=bin/staticalize-macos \
            --include=VERSION \
            --allow-read --allow-write --allow-net main.ts

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.JACK_GITHUB_TOKEN }}
          make_latest: true
          files: |
            bin/*
            action.yaml
            README.md